### PR TITLE
Added support to Farsi

### PR DESCRIPTION
**Pull request by juanroldanbrz**
I added support to Farsi language (Persian)

### CODE REVIEW

**Comment by TakahikoKawasaki** [comment]
May I ask you why you want to add `fa` to `LocaleCode`? I'm just wondering. I'm not against adding `fa`, but at the same time, I don't find a reason to do it.

If `fa` is added to `LocaleCode`, probably other languages that are in `LanguageCode` but not in `LocaleCode` should be added, too.

**Comment by juanroldanbrz** [comment]
Actually, I am trying to use my application with farsi language and also arabian, but arabian is already included.
I am also using other languages supported by your library and the only one which is not it fa.

**Comment by TakahikoKawasaki** [comment]
fa(LanguageCode.fa, CountryCode.IR),

should be changed to

    fa(LanguageCode.fa, null),

If `CountryCode.IR` is important,

    fa_IR(LanguageCode.fa, CountryCode.IR),

should be added.

**Comment by TakahikoKawasaki** [comment]
@juanroldanbrz Could you modify your PR?

**Comment by juanroldanbrz** [comment]
Done! Thank you!

**Comment by TakahikoKawasaki** [comment]
@juanroldanbrz 
I released a new version, 1.21, which includes `fa` and `fa_IR`.

**Pull request merged**
