### PR TITLE
Fix for issue #38

### PR DESCRIPTION
**Pull request by fink-stanislav**
See https://github.com/TakahikoKawasaki/nv-i18n/issues/38

### CODE REVIEW

**Comment by TakahikoKawasaki** [comment]
Thank you for your pull request. I'd like to keep `BYR` and `LTL` for backward compatibility. Could you add `@deprecated` to `BYR` and `LTL` instead of removing them as I did in the past for `LanguageCode.no`?

**Comment by fink-stanislav** [comment]
Hi!

I have reverted removed currencies and marked them as deprecated. Also I have updated CurrencyCodeTest because some methods were not covered. 

Btw, thank you for the library, it really helped.

**Comment by beresfordt** [comment]
Hi,

Looks like the review comment has been addressed; can this be merged? Would be quite useful for me to have Lithuania listed as using the Euro

Thanks

Tom

**Comment by TakahikoKawasaki** [comment]
@fink-stanislav Your suggestion was manually merged (see #38) and nv-i18n-1.24 was released.

**Pull request closed without merging**
