### PR TITLE
Country subdivision codes

### PR DESCRIPTION
**Pull request by tobias-**
This pull request is two commits, the first(b75df66) adds support for country subdivisions (Provinces/States/Counties/Regions etc) as requested in #8 (from 2013) and adds a script for generating the SubDivision enums. The script works by going through all the CountryCode's and parse what unece says about it. I haven't found any better source, but if you have one and like the idea, let me know and I'll parse that instead.

The second commit in this pull request is a run version of it, where all the SubDivisionCodes have been generated and added to CountryCode.

The script has one major caveat; it depends on itself, and does not use the maven cache unless told the absolute path (without variable expansion) to the m2 repository. Modify it in generateSubDivisions.groovy line 12. Otherwise it's simply a matter of running `mvn clean install` (to build the snapshot version and install it into the m2 repository) and then run `mvn -Pgenerate-sub-divisions clean install` to build it. I do _not_ envision it being in the build process at all, and I do _not_ consider the SubDivisionXX.java to be artifacts because they should be version controlled and _not_ autogenerated without manual checking of the result.

The script is in groovy, and uses Sun's JCodeModel to create java code from within the JVM. It's reasonably easy to work with, and you can easily add methods in each CountrySubDivision (name REALLY subject to change). My idea on getByCode() is that it's a member method on the CountryCode enum (i.e. NOT a static method) and simply loops through the countrySubDivisionCodes list.

This is just one idea, but if you have another idea, please use that instead.

Btw, I started implementing an enum for utilizing the subdivision type (provice/region/state etc), but there's an average of one unique type per country, so that was pretty useless.

The source of the subdivisions:
http://www.unece.org/cefact/locode/subdivisions.html

### CODE REVIEW

**Comment by TakahikoKawasaki** [comment]
Great work. I'd like to recommend you to create an independent maven artifact for this code under your GitHub repository. I think your work deserves to be honored as your achievement.

After you finish registering your maven artifact into the Maven Central Repository, I will update README.md of nv-i18n and [my answer](http://stackoverflow.com/a/11084479/1174054) in StackOverflow to mention your work.

**Comment by tobias-** [comment]
I couldn't care less about credits and would gladly sign over the code to you if it meant I wouldn't have to release when you change something in your nv-i18n library, but if you want it as a separate library, I will do that. Since the size of the generated SubDivisions is several magnitudes larger than the rest of the library, I can respect that.

I will update this PR-request when I've released to maven central.

If at any time you change your mind and want to incorporate this into nv-i18n, with any changes, let me know.

Btw, would you be more interested in a fix for #8 that does not build on enums, but instead a database(properties-file or something), and thus will be much smaller to distribute and fewer classes?

**Comment by tobias-** [comment]
Ok, I've added a new repository. Slightly different and would love any comments/suggestions you have.

https://github.com/tobias-/i18n-subdivisions

**Comment by TakahikoKawasaki** [comment]
How quickly you've done it!

I'll take a look, but it will take time due to business. So, of course, you don't have to wait for my review and you can release your subdivisions library at any time.

**Pull request closed without merging**
